### ISSUE TITLE
Empty output with 0 (zero)

### ISSUE THREAD

**Issue by sirotopr** [benwilber/bashids#2]
Running `./bashids -e 0` or `./bashids -e '0'` returns an empty string.
According to feature 1 on hashids' website it should handle zeros:

> Create short unique ids from numbers (positive numbers & zero).

The JavaScript version handles zero correctly.
Am I doing something wrong?

**Comment by sirotopr** [comment]
Encoding 100, 200, ..., 1000, 2000, etc. also outputs nothing.

**Comment by benwilber** [comment]
@sirotopr thanks for the report!  The fix is on master.
